language: python 
python: 
- "3.6"
- "3.7"
env: 
- DJANGO=2.0 DB=postgres
install: 
- pip install -r requirements.txt 
script: 
- python manage.py test
services:
  - postgresql
before_script:
 - psql -c "create user decide with password 'decide'" 
 - psql -c "create database decide owner decide"
 - cd decide
 - python manage.py migrate